name:                hboi
version:             0.1.0.0
github:              "pfcm/hboi"
license:             BSD3
author:              "pfcm"
maintainer:          "pfcmathews@gmail.com"
copyright:           "pfcm"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:          Short description of your package
# category:          Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pfcm/hboi#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs:       src

executables:
  game-person:
    main:            Main.hs
    source-dirs:     app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hboi

tests:
  hboi-units:
    main:            Spec.hs
    source-dirs:     test/units
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hboi
    - hspec
